before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then composer require --dev --no-update phpunit/phpunit ~4; fi

install:  
  - travis_retry composer install --no-interaction --ignore-platform-reqs

language: php
php:
- 7.1
- 5.6
- 5.5
- 5.4
- hhvm
script: phpunit Test.php